### ISSUE TITLE
Suggestion about the api

### ISSUE THREAD

**Issue by Xapuu** [IliaIdakiev/async-render#3]
## Current behavior:

In order to re-load the async renderer, new data must be passed to the `refresh$` Subject inside `AsyncRenderComponent`, which triggers all necessary loads.

## Suggestion

Probably it will be more robust if instead

```ts
asyncRef.refresh$.next();
```

we have something more like

```ts
asyncRef.refresh();
```

which then will handle all necessary load-related operations internally.

**Comment by IliaIdakiev** [comment]
I think that 
```
asyncRef.refresh$.next();
```
is fine since you can either call it like mentioned or do something like 
```
someOtherStream$.pipe(asyncRef.refresh$)
```
which will trigger refresh based on a stream
